# Generated by Django 3.2.3 on 2021-08-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_url_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='redirect_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
